// 계정 데이터. 이 파일만 고치면 됩니다.
// yt: 유튜브 @핸들, ytId: 채널 ID(UC...), ig: 인스타 아이디, tt: 틱톡 아이디, followers: 조사 시점 수치(API 연결 전 표시용)
window.ACCOUNTS=[
{
"id": "d0",
"cat": "comedy",
"name": "원정맨",
"yt": null,
"ytId": null,
"ig": null,
"tt": "ox_zung",
"followers": 50100000,
"desc": "리액션·듀엣 밈 코미디, 한국 최다 팔로워 틱톡커"
},
{
"id": "d1",
"cat": "comedy",
"name": "벨트맨 beltman",
"yt": null,
"ytId": null,
"ig": null,
"tt": "belt_man",
"followers": 4900000,
"desc": "한국 틱톡 상위권 코믹 스킷"
},
{
"id": "d2",
"cat": "comedy",
"name": "숏박스",
"yt": "@shortbox",
"ytId": null,
"ig": null,
"tt": null,
"followers": 4000000,
"desc": "김원훈·조진세·엄지윤의 공감형 하이퍼리얼리즘 스케치"
},
{
"id": "d3",
"cat": "comedy",
"name": "뜬뜬 DdeunDdeun",
"yt": "@ddeunddeun",
"ytId": null,
"ig": null,
"tt": null,
"followers": 3190000,
"desc": "안테나 플러스 운영, 유재석 '핑계고' 중심 토크 코미디"
},
{
"id": "d4",
"cat": "comedy",
"name": "백동욱",
"yt": null,
"ytId": null,
"ig": null,
"tt": "donguk2da",
"followers": 2980000,
"desc": "틱톡 어워즈 2025 올해의 앰배서더, 편집 기법 코믹 숏폼"
},
{
"id": "d5",
"cat": "comedy",
"name": "피식대학",
"yt": "@피식대학",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2840000,
"desc": "이용주·정재형·김민수의 캐릭터 코미디"
},
{
"id": "d6",
"cat": "comedy",
"name": "장삐쭈",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 2450000,
"desc": "병맛 더빙·애니메이션 코미디, 메타코미디 소속"
},
{
"id": "d7",
"cat": "comedy",
"name": "빠더너스",
"yt": "@bdns",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2390000,
"desc": "문상훈의 캐릭터 스케치 코미디"
},
{
"id": "d8",
"cat": "comedy",
"name": "하다 Hada",
"yt": null,
"ytId": null,
"ig": null,
"tt": "hada.kr",
"followers": 2300000,
"desc": "틱톡 어워즈 2024 올해의 앰배서더, 코믹 스킷·챌린지"
},
{
"id": "d9",
"cat": "comedy",
"name": "흔한남매",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 2250000,
"desc": "한으뜸·장다운의 남매 콩트·상황극"
},
{
"id": "d10",
"cat": "comedy",
"name": "고로켓",
"yt": null,
"ytId": null,
"ig": null,
"tt": "hea_dli_",
"followers": 2200000,
"desc": "틱톡 어워즈 2024 베스트 케미(혜다&고로켓), 코믹 상황극"
},
{
"id": "d11",
"cat": "comedy",
"name": "공대생 변승주 DS",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 2160000,
"desc": "실험·몰카·미션형 코믹 콘텐츠"
},
{
"id": "d12",
"cat": "comedy",
"name": "낄낄상회",
"yt": "@ggilggilmarket",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2130000,
"desc": "장윤석·임종혁 개그맨 듀오, 웹드라마형 코미디"
},
{
"id": "d13",
"cat": "comedy",
"name": "너덜트",
"yt": "@NERDULT",
"ytId": null,
"ig": "nerd_ult",
"tt": null,
"followers": 2110000,
"desc": "직장·일상 스케치 코미디, 인스타 @nerd_ult 병행"
},
{
"id": "d14",
"cat": "comedy",
"name": "보물섬",
"yt": null,
"ytId": "UC9ZLv1m7QDLv991X1-p50AA",
"ig": null,
"tt": null,
"followers": 2060000,
"desc": "몰래카메라·성대모사·상황극 숏폼"
},
{
"id": "d15",
"cat": "comedy",
"name": "퇴경아 약먹자",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 2010000,
"desc": "약사 크리에이터의 언어유희·패러디 댄스 코미디"
},
{
"id": "d16",
"cat": "comedy",
"name": "랄랄",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1960000,
"desc": "부캐 '이명화' 캐릭터 코미디"
},
{
"id": "d17",
"cat": "comedy",
"name": "유병재",
"yt": "@KoreanCryingGuy",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1860000,
"desc": "풍자·블랙코미디 스케치"
},
{
"id": "d18",
"cat": "comedy",
"name": "더블비",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1720000,
"desc": "패러디·몰카·참교육 코미디"
},
{
"id": "d19",
"cat": "comedy",
"name": "조재원",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1540000,
"desc": "몰카·상황극 중심 개그"
},
{
"id": "d20",
"cat": "comedy",
"name": "꽥보석 boseok",
"yt": null,
"ytId": null,
"ig": null,
"tt": "boseok751",
"followers": 1500000,
"desc": "코믹 상황극·연애 스킷"
},
{
"id": "d21",
"cat": "comedy",
"name": "동네놈들",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1430000,
"desc": "안진호·정재형·최부기의 몰카·상황극"
},
{
"id": "d22",
"cat": "comedy",
"name": "급식왕",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1390000,
"desc": "학교생활 캐릭터 상황극"
},
{
"id": "d23",
"cat": "comedy",
"name": "박막례 할머니",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1330000,
"desc": "70대 할머니의 날것 리액션 코미디"
},
{
"id": "d24",
"cat": "comedy",
"name": "낭만박상환",
"yt": null,
"ytId": "UC6yEsiYQjnLve24g34lVa1w",
"ig": null,
"tt": null,
"followers": 1080000,
"desc": "하루 여러 편 올리는 숏폼 개그"
},
{
"id": "d25",
"cat": "comedy",
"name": "개그콘서트 공식",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1000000,
"desc": "KBS 개그콘서트 코너 풀영상·쇼츠"
},
{
"id": "d26",
"cat": "comedy",
"name": "메타코미디클럽",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 992000,
"desc": "메타코미디 레이블 공식 코미디 쇼"
},
{
"id": "d27",
"cat": "comedy",
"name": "배꼽빌라",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 910000,
"desc": "김승진·유룡·이재훈의 몰카 코미디"
},
{
"id": "d28",
"cat": "comedy",
"name": "킥서비스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 872000,
"desc": "정진하·박진호의 '2032년 미래 일상' 스케치"
},
{
"id": "d29",
"cat": "comedy",
"name": "스낵타운",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 853000,
"desc": "이재율·강현석의 빠른 템포 병맛 스케치, 메타코미디"
},
{
"id": "d30",
"cat": "comedy",
"name": "강유미 좋아서 하는 채널",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 840000,
"desc": "강유미의 캐릭터 연기·ASMR 상황극"
},
{
"id": "d31",
"cat": "comedy",
"name": "뀨러기",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 690000,
"desc": "개그 상황극·콩트"
},
{
"id": "d32",
"cat": "comedy",
"name": "김동희 세계관",
"yt": "@김동희세계관",
"ytId": null,
"ig": null,
"tt": "kdh_uv",
"followers": 623000,
"desc": "게임 패러디 기반 1인 캐릭터 세계관 숏폼 (유튜브 기준 수치)"
},
{
"id": "d33",
"cat": "comedy",
"name": "혜다",
"yt": null,
"ytId": null,
"ig": null,
"tt": "yourhyeda",
"followers": 620000,
"desc": "틱톡 어워즈 2024 베스트 케미(혜다&고로켓), 코믹 상황극"
},
{
"id": "d34",
"cat": "comedy",
"name": "꼰대희",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 620000,
"desc": "김대희의 '밥묵자' 2인극 콩트"
},
{
"id": "d35",
"cat": "comedy",
"name": "깨방정",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 610000,
"desc": "개그 상황극 코미디"
},
{
"id": "d36",
"cat": "comedy",
"name": "조충현",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 590000,
"desc": "메타코미디 소속 개그맨 조충현"
},
{
"id": "d37",
"cat": "comedy",
"name": "코믹마트",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 580000,
"desc": "코믹 상황극·콩트"
},
{
"id": "d38",
"cat": "comedy",
"name": "빵송국",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 577000,
"desc": "곽범·이창호의 '매드몬스터' 세계관 코미디, 메타코미디"
},
{
"id": "d39",
"cat": "comedy",
"name": "드립팩토리",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 570000,
"desc": "드립·개그 숏폼"
},
{
"id": "d40",
"cat": "comedy",
"name": "양세브라더스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 570000,
"desc": "양세형·양세찬 형제의 코미디·먹방"
},
{
"id": "d41",
"cat": "comedy",
"name": "젼언니",
"yt": null,
"ytId": null,
"ig": null,
"tt": "jeon_unni",
"followers": 570000,
"desc": "틱톡 어워즈 2024 올해의 크리에이터, 코믹 일상 상황극"
},
{
"id": "d42",
"cat": "comedy",
"name": "1등 미디어",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 530000,
"desc": "코미디 상황극 채널"
},
{
"id": "d43",
"cat": "comedy",
"name": "닛몰캐쉬",
"yt": null,
"ytId": null,
"ig": null,
"tt": "needmorecash_vdbh",
"followers": 490000,
"desc": "틱톡 어워즈 코리아 2024 코미디 크리에이터 수상, 상황극"
},
{
"id": "d44",
"cat": "comedy",
"name": "이수근 채널",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 440000,
"desc": "개그맨 이수근의 개인 채널"
},
{
"id": "d45",
"cat": "comedy",
"name": "얼간김준호",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 430000,
"desc": "개그맨 김준호의 개인 채널"
},
{
"id": "d46",
"cat": "comedy",
"name": "면상들",
"yt": "@theMSD",
"ytId": null,
"ig": null,
"tt": null,
"followers": 412000,
"desc": "이선민·조훈의 몰카·스케치, 메타코미디"
},
{
"id": "d47",
"cat": "comedy",
"name": "폭소바겐",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 360000,
"desc": "박형민·정승우의 공익 몰카 코미디"
},
{
"id": "d48",
"cat": "comedy",
"name": "쑥쑥 SsookSsook",
"yt": "@Ssook_Ssook",
"ytId": null,
"ig": null,
"tt": null,
"followers": 352000,
"desc": "양세찬·안테나 플러스의 기획회의형 코미디"
},
{
"id": "d49",
"cat": "comedy",
"name": "노홍철",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 340000,
"desc": "노홍철의 셀프 코미디"
},
{
"id": "d50",
"cat": "comedy",
"name": "코테고리",
"yt": "@코테고리",
"ytId": null,
"ig": null,
"tt": "cotegory",
"followers": 333000,
"desc": "고빈도 숏폼 개그, 유튜브 @코테고리 병행 (유튜브 기준 수치)"
},
{
"id": "d51",
"cat": "comedy",
"name": "욜로코믹스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 310000,
"desc": "코믹 상황극·콩트"
},
{
"id": "d52",
"cat": "comedy",
"name": "쓰복만",
"yt": "@smurf0131",
"ytId": null,
"ig": null,
"tt": null,
"followers": 292000,
"desc": "성우 김보민의 성대모사·캐릭터 코미디 숏폼"
},
{
"id": "d53",
"cat": "comedy",
"name": "전핑콩",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 242000,
"desc": "한·미·일 문화 비교 캐릭터 상황극 숏폼"
},
{
"id": "d54",
"cat": "comedy",
"name": "당황TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 210000,
"desc": "몰카·당황 리액션 코미디"
},
{
"id": "d55",
"cat": "comedy",
"name": "The면상",
"yt": "@the_myeonsang",
"ytId": null,
"ig": null,
"tt": null,
"followers": 199000,
"desc": "면상들의 서브 채널"
},
{
"id": "d56",
"cat": "comedy",
"name": "룰루보이",
"yt": null,
"ytId": null,
"ig": null,
"tt": "iamluluboi",
"followers": 190000,
"desc": "틱톡 어워즈 2024 올해의 라이징 크리에이터"
},
{
"id": "d57",
"cat": "comedy",
"name": "걸깝스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 120000,
"desc": "장하나·황정혜의 개그맨 대상 몰카"
},
{
"id": "d58",
"cat": "politics",
"name": "MBCNEWS",
"yt": "@MBCNEWS11",
"ytId": null,
"ig": null,
"tt": null,
"followers": 6070000,
"desc": "MBC 보도국 공식, 언론사 유튜브 구독자 1위 · 언론"
},
{
"id": "d59",
"cat": "politics",
"name": "YTN",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 4580000,
"desc": "24시간 보도전문채널 공식 뉴스 · 언론"
},
{
"id": "d60",
"cat": "politics",
"name": "SBS 뉴스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 4430000,
"desc": "SBS 보도본부 공식 뉴스 · 언론"
},
{
"id": "d61",
"cat": "politics",
"name": "슈카월드",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 3650000,
"desc": "경제·시사 이슈 해설 토크 · 경제·시사"
},
{
"id": "d62",
"cat": "politics",
"name": "뉴스TVCHOSUN",
"yt": "@tvchosunnews",
"ytId": null,
"ig": null,
"tt": null,
"followers": 3100000,
"desc": "TV조선 보도본부 공식 뉴스 · 언론(보수지)"
},
{
"id": "d63",
"cat": "politics",
"name": "MBN News",
"yt": "@mbn",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2600000,
"desc": "MBN 매일방송 공식 뉴스 · 언론"
},
{
"id": "d64",
"cat": "politics",
"name": "김어준의 뉴스공장",
"yt": "@gyeomsonisnothing",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2300000,
"desc": "아침 생방송 시사 토크 · 진보"
},
{
"id": "d65",
"cat": "politics",
"name": "연합뉴스TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1890000,
"desc": "연합뉴스 보도전문채널 · 언론"
},
{
"id": "d66",
"cat": "politics",
"name": "진성호방송",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1850000,
"desc": "전 정치인 진성호의 시사 방송 · 보수"
},
{
"id": "d67",
"cat": "politics",
"name": "뉴스타파",
"yt": "@news_tapa",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1800000,
"desc": "비영리 독립 탐사보도 · 진보"
},
{
"id": "d68",
"cat": "politics",
"name": "조선일보",
"yt": "@chosunmedia",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1800000,
"desc": "조선일보 공식 유튜브 · 언론(보수지)"
},
{
"id": "d69",
"cat": "politics",
"name": "펜앤마이크TV",
"yt": "@PennMike",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1710000,
"desc": "정규재 중심 시사 해설 · 보수"
},
{
"id": "d70",
"cat": "politics",
"name": "이재명 TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1660000,
"desc": "이재명 대통령 개인 채널 · 진보"
},
{
"id": "d71",
"cat": "politics",
"name": "신의한수",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1580000,
"desc": "신혜식 대표의 시사 채널 · 보수"
},
{
"id": "d72",
"cat": "politics",
"name": "지식한입",
"yt": "@지식한입",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1500000,
"desc": "시사·경제·국제 이슈 해설 교양 · 경제·시사"
},
{
"id": "d73",
"cat": "politics",
"name": "사람사는세상 노무현재단",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1440000,
"desc": "노무현재단 공식, 시사 대담 · 진보"
},
{
"id": "d74",
"cat": "politics",
"name": "채널A 뉴스TOP10",
"yt": "@channela-newstop10",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1400000,
"desc": "채널A 시사 프로그램 · 언론"
},
{
"id": "d75",
"cat": "politics",
"name": "KBS 1라디오",
"yt": "@kbs_1radio",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1400000,
"desc": "KBS 1라디오 시사·뉴스 · 언론"
},
{
"id": "d76",
"cat": "politics",
"name": "김지윤의 지식Play",
"yt": "@kjy_play",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1400000,
"desc": "정치학자 김지윤의 국제정치 해설 · 경제·시사"
},
{
"id": "d77",
"cat": "politics",
"name": "KNN NEWS",
"yt": "@knn_news",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1400000,
"desc": "부산·경남 민방 KNN 뉴스 · 언론"
},
{
"id": "d78",
"cat": "politics",
"name": "고성국TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1330000,
"desc": "정치평론가 고성국의 시사 채널 · 보수"
},
{
"id": "d79",
"cat": "politics",
"name": "딴지방송국",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1330000,
"desc": "김어준의 딴지일보 방송 · 진보"
},
{
"id": "d80",
"cat": "politics",
"name": "서울의소리",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1330000,
"desc": "백은종 대표의 인터넷 언론 · 진보"
},
{
"id": "d81",
"cat": "politics",
"name": "시사포커스TV",
"yt": "@sisafocustv",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1300000,
"desc": "시사 방송 채널 · 보수"
},
{
"id": "d82",
"cat": "politics",
"name": "성제준TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1060000,
"desc": "유튜버 성제준의 시사 채널 · 보수"
},
{
"id": "d83",
"cat": "politics",
"name": "새날",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1000000,
"desc": "시사 토크 방송 · 진보"
},
{
"id": "d84",
"cat": "politics",
"name": "JTV뉴스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1000000,
"desc": "전주방송 JTV 뉴스 · 언론"
},
{
"id": "d85",
"cat": "politics",
"name": "전옥현 안보정론TV",
"yt": "@tv-gs4of",
"ytId": null,
"ig": null,
"tt": null,
"followers": 995000,
"desc": "전 국정원 차장의 안보·시사 · 보수"
},
{
"id": "d86",
"cat": "politics",
"name": "가로세로연구소",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 990000,
"desc": "김세의 대표의 시사 폭로 채널 · 보수"
},
{
"id": "d87",
"cat": "politics",
"name": "GROUND C 그라운드씨",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 983000,
"desc": "시사 해설 채널 · 보수"
},
{
"id": "d88",
"cat": "politics",
"name": "매일경제TV",
"yt": "@mkeconomy_tv",
"ytId": null,
"ig": null,
"tt": null,
"followers": 954000,
"desc": "매일경제 경제 전문 방송 · 경제·시사"
},
{
"id": "d89",
"cat": "politics",
"name": "스픽스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 950000,
"desc": "시사 뉴스 해설 · 진보"
},
{
"id": "d90",
"cat": "politics",
"name": "YTN 라디오",
"yt": "@ytnradio",
"ytId": null,
"ig": null,
"tt": null,
"followers": 920000,
"desc": "YTN 라디오 시사 프로그램 · 언론"
},
{
"id": "d91",
"cat": "politics",
"name": "성창경TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 900000,
"desc": "전 KBS 기자 성창경의 시사 채널 · 보수"
},
{
"id": "d92",
"cat": "politics",
"name": "이봉규TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 900000,
"desc": "시사평론가 이봉규 · 보수"
},
{
"id": "d93",
"cat": "politics",
"name": "전한길뉴스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 842000,
"desc": "한국사 강사 전한길의 시사 채널 · 보수"
},
{
"id": "d94",
"cat": "politics",
"name": "SBS 시사교양 라디오 시교라",
"yt": "@sbsradio_sisa",
"ytId": null,
"ig": null,
"tt": null,
"followers": 795000,
"desc": "SBS 라디오 시사교양 · 언론"
},
{
"id": "d95",
"cat": "politics",
"name": "연합뉴스경제TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 768000,
"desc": "연합뉴스TV 경제 전문 · 경제·시사"
},
{
"id": "d96",
"cat": "politics",
"name": "김채환의 시사이다",
"yt": "@sisa",
"ytId": null,
"ig": null,
"tt": null,
"followers": 749000,
"desc": "김채환의 시사 해설 · 보수"
},
{
"id": "d97",
"cat": "politics",
"name": "정청래TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 676000,
"desc": "더불어민주당 정청래 의원 · 진보"
},
{
"id": "d98",
"cat": "politics",
"name": "매일신문",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 668000,
"desc": "대구 매일신문 유튜브 · 언론(보수지)"
},
{
"id": "d99",
"cat": "politics",
"name": "한국의목소리",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 652000,
"desc": "시사 채널 · 보수"
},
{
"id": "d100",
"cat": "politics",
"name": "이대남의우회전",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 640000,
"desc": "청년 보수 시사 채널 · 보수"
},
{
"id": "d101",
"cat": "politics",
"name": "중앙일보",
"yt": "@joongangilbo",
"ytId": null,
"ig": null,
"tt": null,
"followers": 598000,
"desc": "중앙일보 공식 유튜브 · 언론"
},
{
"id": "d102",
"cat": "politics",
"name": "호밀밭의 우원재",
"yt": "@wonjaewoo",
"ytId": null,
"ig": null,
"tt": null,
"followers": 592000,
"desc": "우원재의 시사 비평 · 보수"
},
{
"id": "d103",
"cat": "politics",
"name": "전주MBC News",
"yt": "@jmbc_news",
"ytId": null,
"ig": null,
"tt": null,
"followers": 590000,
"desc": "전주MBC 뉴스 · 언론"
},
{
"id": "d104",
"cat": "politics",
"name": "황기자",
"yt": "@hwanggija",
"ytId": null,
"ig": null,
"tt": null,
"followers": 581000,
"desc": "1인 시사 기자 채널 · 보수"
},
{
"id": "d105",
"cat": "politics",
"name": "정광용 레지스탕스TV",
"yt": "@tvtv-rc1hd",
"ytId": null,
"ig": null,
"tt": null,
"followers": 578000,
"desc": "정광용의 시사 채널 · 보수"
},
{
"id": "d106",
"cat": "politics",
"name": "미디어몽구",
"yt": "@mediamongu",
"ytId": null,
"ig": null,
"tt": null,
"followers": 545000,
"desc": "1인 미디어 현장 취재 · 진보"
},
{
"id": "d107",
"cat": "politics",
"name": "주블리 김병주",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 504000,
"desc": "더불어민주당 김병주 의원 · 진보"
},
{
"id": "d108",
"cat": "politics",
"name": "VOA 한국어",
"yt": "@voakorea",
"ytId": null,
"ig": null,
"tt": null,
"followers": 492000,
"desc": "미국의소리 한국어 뉴스 · 언론"
},
{
"id": "d109",
"cat": "politics",
"name": "박선원TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 475000,
"desc": "더불어민주당 박선원 의원 · 진보"
},
{
"id": "d110",
"cat": "politics",
"name": "MBC 100분 토론",
"yt": "@mbc100",
"ytId": null,
"ig": null,
"tt": null,
"followers": 465000,
"desc": "MBC 시사 토론 프로그램 · 언론"
},
{
"id": "d111",
"cat": "politics",
"name": "바른소리TV",
"yt": "@바른소리tv",
"ytId": null,
"ig": null,
"tt": null,
"followers": 464000,
"desc": "시사 채널 · 보수"
},
{
"id": "d112",
"cat": "politics",
"name": "추미애TV",
"yt": "@choo_miae",
"ytId": null,
"ig": null,
"tt": null,
"followers": 320000,
"desc": "더불어민주당 추미애 의원 · 진보"
},
{
"id": "d113",
"cat": "politics",
"name": "주진우의 이슈 해설",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 307000,
"desc": "국민의힘 주진우 의원 · 보수"
},
{
"id": "d114",
"cat": "politics",
"name": "김민석 TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 272000,
"desc": "김민석 국무총리 개인 채널 · 진보"
},
{
"id": "d115",
"cat": "politics",
"name": "뉴스핌TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 258000,
"desc": "뉴스핌 통신사 영상 채널 · 언론"
},
{
"id": "d116",
"cat": "politics",
"name": "해준TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 255000,
"desc": "시사 채널 · 보수"
},
{
"id": "d117",
"cat": "politics",
"name": "김성회의 옳은소리",
"yt": "@김성회의옳은소리",
"ytId": null,
"ig": null,
"tt": null,
"followers": 225000,
"desc": "더불어민주당 김성회 의원 · 진보"
},
{
"id": "d118",
"cat": "politics",
"name": "대한민국 NOW (KTV)",
"yt": "@ktv_koreanow",
"ytId": null,
"ig": null,
"tt": null,
"followers": 216000,
"desc": "KTV 국민방송 정책·뉴스 · 언론"
},
{
"id": "d119",
"cat": "politics",
"name": "박주현변호사TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 206000,
"desc": "박주현 변호사의 시사 채널 · 보수"
},
{
"id": "d120",
"cat": "politics",
"name": "한동훈입니다",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 188000,
"desc": "한동훈 전 국민의힘 대표 · 보수"
},
{
"id": "d121",
"cat": "politics",
"name": "VON뉴스",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 163000,
"desc": "인터넷 뉴스 채널 · 보수"
},
{
"id": "d122",
"cat": "politics",
"name": "이정주의 질문하는 기자",
"yt": "@cbsasklive",
"ytId": null,
"ig": null,
"tt": null,
"followers": 158000,
"desc": "CBS 이정주 기자 · 언론"
},
{
"id": "d123",
"cat": "politics",
"name": "나경원TV",
"yt": "@together-we-can.",
"ytId": null,
"ig": null,
"tt": null,
"followers": 145000,
"desc": "국민의힘 나경원 의원 · 보수"
},
{
"id": "d124",
"cat": "politics",
"name": "자유대학",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 140000,
"desc": "청년 보수 단체 채널 · 보수"
},
{
"id": "d125",
"cat": "politics",
"name": "TV허재현",
"yt": "@repoacttv",
"ytId": null,
"ig": null,
"tt": null,
"followers": 137000,
"desc": "허재현 기자의 시사 채널 · 진보"
},
{
"id": "d126",
"cat": "politics",
"name": "우원식 TV",
"yt": "@wonsikw",
"ytId": null,
"ig": null,
"tt": null,
"followers": 132000,
"desc": "우원식 국회의장 개인 채널 · 진보"
},
{
"id": "d127",
"cat": "politics",
"name": "이승만TV",
"yt": "@syngmanschool",
"ytId": null,
"ig": null,
"tt": null,
"followers": 124000,
"desc": "이승만학당의 역사·시사 · 보수"
},
{
"id": "d128",
"cat": "politics",
"name": "JTBC News",
"yt": "@jtbc_news",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "JTBC 보도국 공식, 속보·쇼츠 · 언론"
},
{
"id": "d129",
"cat": "politics",
"name": "14F 일사에프",
"yt": "@14F",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "MBC의 MZ 대상 숏폼 뉴스 해설 · 언론"
},
{
"id": "d130",
"cat": "politics",
"name": "스브스뉴스",
"yt": "@subusunews",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "SBS의 젊은 층 대상 숏폼 이슈 해설 · 언론"
},
{
"id": "d131",
"cat": "politics",
"name": "오마이TV",
"yt": "@ohmytv",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "오마이뉴스 영상 채널, 정치 현장 중계 · 진보"
},
{
"id": "d132",
"cat": "politics",
"name": "매불쇼",
"yt": "@maebulshow",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "최욱 진행 시사 풍자 토크쇼 · 진보"
},
{
"id": "d133",
"cat": "politics",
"name": "배승희 변호사",
"yt": "@Baeseunghee",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "변호사의 정치·법률 이슈 해설 · 보수"
},
{
"id": "d134",
"cat": "survival",
"name": "리랑온에어",
"yt": "@RirangOnAir",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1200000,
"desc": "극한 날씨 속 오지 솔로 비박 캠핑"
},
{
"id": "d135",
"cat": "survival",
"name": "희철리즘",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 870000,
"desc": "오지·극한 여행 탐방"
},
{
"id": "d136",
"cat": "survival",
"name": "초마드 CHOMAD",
"yt": "@CHOMAD",
"ytId": null,
"ig": null,
"tt": null,
"followers": 790000,
"desc": "오토바이 세계일주·오지 바이크 투어링"
},
{
"id": "d137",
"cat": "survival",
"name": "입질의추억TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 760000,
"desc": "어류 칼럼니스트 김지민의 수산물·낚시"
},
{
"id": "d138",
"cat": "survival",
"name": "조조캠핑",
"yt": "@jojocamping",
"ytId": null,
"ig": null,
"tt": null,
"followers": 740000,
"desc": "반려견과 개조 갤로퍼로 떠나는 차박 캠핑"
},
{
"id": "d139",
"cat": "survival",
"name": "앵쩡TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 580000,
"desc": "낚시·해산물 요리·먹방·캠핑"
},
{
"id": "d140",
"cat": "survival",
"name": "은하캠핑",
"yt": "@eunhacamping",
"ytId": null,
"ig": null,
"tt": null,
"followers": 570000,
"desc": "특전사 출신 박은하의 생존 캠핑·부시크래프트"
},
{
"id": "d141",
"cat": "survival",
"name": "박진우 JINU",
"yt": "@TEAMJINU",
"ytId": null,
"ig": null,
"tt": null,
"followers": 470000,
"desc": "캠핑·아웃도어·여행 브이로그"
},
{
"id": "d142",
"cat": "survival",
"name": "진석기시대",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 380000,
"desc": "직접 잡은 물고기 요리와 낚시 로드트립"
},
{
"id": "d143",
"cat": "survival",
"name": "슬기로운 캠핑생활",
"yt": "@korea_travel",
"ytId": null,
"ig": null,
"tt": null,
"followers": 325000,
"desc": "캠핑·국내 아웃도어 모험 (채널명 변경됨)"
},
{
"id": "d144",
"cat": "survival",
"name": "인어교주해적단",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 320000,
"desc": "낚시·수산물·바다 콘텐츠"
},
{
"id": "d145",
"cat": "survival",
"name": "캐럿맨 여행기",
"yt": "@carrotman1198",
"ytId": null,
"ig": null,
"tt": null,
"followers": 313000,
"desc": "차박·캠핑 여행 브이로그"
},
{
"id": "d146",
"cat": "survival",
"name": "캠핑한끼",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 300000,
"desc": "영상미 좋은 캠핑 요리"
},
{
"id": "d147",
"cat": "survival",
"name": "캠핑쥐 campingG",
"yt": "@campingG",
"ytId": null,
"ig": null,
"tt": null,
"followers": 288000,
"desc": "솔로 캠핑·감성 캠핑 브이로그"
},
{
"id": "d148",
"cat": "survival",
"name": "리얼깽TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 260000,
"desc": "강원 고성 어촌 생활, 바다낚시와 어판장 경매"
},
{
"id": "d149",
"cat": "survival",
"name": "도토리TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 250000,
"desc": "캠핑·차박 브이로그"
},
{
"id": "d150",
"cat": "survival",
"name": "토리 캠핑 TORI CAMP",
"yt": null,
"ytId": null,
"ig": "torii_camp",
"tt": null,
"followers": 231000,
"desc": "캠핑·아웃도어 인스타 크리에이터"
},
{
"id": "d151",
"cat": "survival",
"name": "캠핑카조아",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 198000,
"desc": "캠핑카·차박 캠핑"
},
{
"id": "d152",
"cat": "survival",
"name": "크크민TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 180000,
"desc": "낚시 유튜버"
},
{
"id": "d153",
"cat": "survival",
"name": "수산물을부탁해TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 170000,
"desc": "낚시·수산물 전문"
},
{
"id": "d154",
"cat": "survival",
"name": "즐거운일상 Enjoy Life",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 140000,
"desc": "낚시·아웃도어 일상"
},
{
"id": "d155",
"cat": "survival",
"name": "황도이장",
"yt": "@Hwang-do",
"ytId": null,
"ig": null,
"tt": null,
"followers": 138000,
"desc": "섬 생활·자연 속 생존형 브이로그"
},
{
"id": "d156",
"cat": "survival",
"name": "보물창고 TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 128000,
"desc": "캠핑 장비·캠핑 콘텐츠"
},
{
"id": "d157",
"cat": "survival",
"name": "팀쎈언니",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 120000,
"desc": "여성 낚시 크리에이터"
},
{
"id": "d158",
"cat": "survival",
"name": "준식이",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 113000,
"desc": "캠핑·차박 브이로그"
},
{
"id": "d159",
"cat": "survival",
"name": "다리네TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 111000,
"desc": "생활낚시·바다낚시"
},
{
"id": "d160",
"cat": "survival",
"name": "힛뜨TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 110000,
"desc": "낚시 채널"
},
{
"id": "d161",
"cat": "survival",
"name": "초짜낚시TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 110000,
"desc": "초보 낚시 가이드"
},
{
"id": "d162",
"cat": "survival",
"name": "허기자TV",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 100000,
"desc": "낚시 채널"
},
{
"id": "d163",
"cat": "survival",
"name": "낚시 시간",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 100000,
"desc": "낚시 채널"
},
{
"id": "d164",
"cat": "survival",
"name": "빡가능",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "한겨울·암반·무인도 야생 캠핑"
},
{
"id": "d165",
"cat": "couple",
"name": "CuRe 구래",
"yt": "@cure0721",
"ytId": null,
"ig": null,
"tt": null,
"followers": 22900000,
"desc": "한국·베트남 커플의 일상·먹방·밈 숏폼, 국내 커플 채널 1위"
},
{
"id": "d166",
"cat": "couple",
"name": "진우와 해티",
"yt": "@jinandhattie",
"ytId": null,
"ig": null,
"tt": null,
"followers": 8000000,
"desc": "배우 진우와 영국인 해티 부부의 문화차이 밈, 틱톡 310만+"
},
{
"id": "d167",
"cat": "couple",
"name": "사샤와 제이",
"yt": "@Sasha-Jay",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2950000,
"desc": "한국인 남편과 벨라루스 아내의 커플 일상·몰카"
},
{
"id": "d168",
"cat": "couple",
"name": "뽀송한 준 bosungjun",
"yt": "@bosungjun",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2290000,
"desc": "박보성·김민준 커플 채널, 일상·라이브"
},
{
"id": "d169",
"cat": "couple",
"name": "엔조이커플",
"yt": "@enjoycouple",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2230000,
"desc": "손민수·임라라 개그맨 커플의 몰카·코미디"
},
{
"id": "d170",
"cat": "couple",
"name": "준 오브 다샤",
"yt": "@JuneOfDasha",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1670000,
"desc": "한국 남편·러시아 아내 국제부부 브이로그"
},
{
"id": "d171",
"cat": "couple",
"name": "성수커플",
"yt": "@SSCouple",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1100000,
"desc": "남자친구의 입담이 특징인 연애 일상"
},
{
"id": "d172",
"cat": "couple",
"name": "토모토모",
"yt": "@zzangtomo",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1050000,
"desc": "한일 커플의 일본 생활·데이트 숏폼"
},
{
"id": "d173",
"cat": "couple",
"name": "소근커플",
"yt": "@소근커플",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1040000,
"desc": "9년 연애 후 결혼한 음악 전공 커플 브이로그"
},
{
"id": "d174",
"cat": "couple",
"name": "채꾸똥꾸",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 924000,
"desc": "20대 동갑 커플 일상 (2023년 결별 발표, 활동 중단 가능)"
},
{
"id": "d175",
"cat": "couple",
"name": "연스커플",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 864000,
"desc": "신혼 컨셉 커플 일상·장난"
},
{
"id": "d176",
"cat": "couple",
"name": "유어온리젠",
"yt": "@youronlyjen",
"ytId": null,
"ig": null,
"tt": null,
"followers": 630000,
"desc": "덴마크 남성과 중국계 덴마크 여자친구의 한국 데이트 브이로그"
},
{
"id": "d177",
"cat": "couple",
"name": "소중커플",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 557000,
"desc": "9년차 장기연애 커플, 기념일 이벤트·연애 조언"
},
{
"id": "d178",
"cat": "couple",
"name": "제주커플",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 530000,
"desc": "제주 거주 커플의 일상 숏폼"
},
{
"id": "d179",
"cat": "couple",
"name": "큐티츄티",
"yt": "@CutieChuti",
"ytId": null,
"ig": null,
"tt": null,
"followers": 520000,
"desc": "커플 일상·코믹 숏폼"
},
{
"id": "d180",
"cat": "couple",
"name": "김치와 바게뜨",
"yt": "@kimchi_baguette",
"ytId": null,
"ig": null,
"tt": null,
"followers": 457000,
"desc": "한국 남편·프랑스 아내 국제부부 가족 일상"
},
{
"id": "d181",
"cat": "couple",
"name": "엔비커플",
"yt": "@NBcouple",
"ytId": null,
"ig": null,
"tt": null,
"followers": 440000,
"desc": "한국인 BD와 마케도니아인 나타샤의 서울 일상"
},
{
"id": "d182",
"cat": "couple",
"name": "헤이킨",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 430000,
"desc": "커플 채널 (IMR 2026 커플 채널 10위)"
},
{
"id": "d183",
"cat": "couple",
"name": "조이차니",
"yt": "@joyofchanlife",
"ytId": null,
"ig": null,
"tt": null,
"followers": 259000,
"desc": "한국·영국 국제부부, 런던 생활 브이로그"
},
{
"id": "d184",
"cat": "couple",
"name": "서가네 국제부부",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 200000,
"desc": "한국 남편·러시아 아내 국제부부 일상"
},
{
"id": "d185",
"cat": "couple",
"name": "투하트원서울",
"yt": "@2hearts1seoul",
"ytId": null,
"ig": null,
"tt": null,
"followers": 170000,
"desc": "한국 남편 규호·캐나다 아내 세라, 문화 차이 콘텐츠"
},
{
"id": "d186",
"cat": "couple",
"name": "나나소나윤",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 170000,
"desc": "한국 남편·일본 아내 국제부부 일상"
},
{
"id": "d187",
"cat": "couple",
"name": "여보부부",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 150000,
"desc": "한국 아내·우크라이나 남편 국제부부"
},
{
"id": "d188",
"cat": "couple",
"name": "디토이",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 150000,
"desc": "한국 남성·베트남 여자친구 국제커플"
},
{
"id": "d189",
"cat": "couple",
"name": "아로치카",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 130000,
"desc": "한국 남편·일본 아내 국제부부"
},
{
"id": "d190",
"cat": "drama",
"name": "하이틴에이저",
"yt": "@hi-teenager",
"ytId": null,
"ig": null,
"tt": null,
"followers": 3720000,
"desc": "플레이타운 산하 웹드라마, 학원물·직장물"
},
{
"id": "d191",
"cat": "drama",
"name": "치즈필름",
"yt": "@CheezeFilm_",
"ytId": null,
"ig": null,
"tt": null,
"followers": 3310000,
"desc": "10대의 사랑·우정·학교 이슈 웹드라마"
},
{
"id": "d192",
"cat": "drama",
"name": "플레이리스트 오리지널",
"yt": "@PlaylistOriginals",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2390000,
"desc": "에이틴·연애플레이리스트 등 로맨스 웹드라마"
},
{
"id": "d193",
"cat": "drama",
"name": "띱 Deep",
"yt": "@_deep",
"ytId": null,
"ig": null,
"tt": null,
"followers": 2300000,
"desc": "배우 3인의 공감형 상황극 스케치 드라마, 반전 엔딩"
},
{
"id": "d194",
"cat": "drama",
"name": "tvN D STORY",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 1830000,
"desc": "CJ ENM tvN D의 Z세대 타깃 디지털 웹드라마"
},
{
"id": "d195",
"cat": "drama",
"name": "콬TV KOK TV",
"yt": "@koktv_official",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1730000,
"desc": "와이낫미디어 운영, 일진에게 찍혔을 때 등 로맨스 웹드라마"
},
{
"id": "d196",
"cat": "drama",
"name": "뷰티풀너드",
"yt": "@뷰티풀너드",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1510000,
"desc": "페이크다큐·웹드라마 형식의 풍자 코미디"
},
{
"id": "d197",
"cat": "drama",
"name": "짧은대본",
"yt": "@short_paper",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1430000,
"desc": "학생·커플·친구 일상의 캐릭터 에피소드, '맑눈광' 배출"
},
{
"id": "d198",
"cat": "drama",
"name": "사내뷰공업",
"yt": "@beautyfool",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1250000,
"desc": "'우당탕탕 알바 공감', '빌런' 시리즈 1인 공감 상황극"
},
{
"id": "d199",
"cat": "drama",
"name": "픽고 PICKGO",
"yt": "@PICKGO",
"ytId": null,
"ig": null,
"tt": null,
"followers": 1200000,
"desc": "20대 일상·연애 세계관 연결형 옴니버스 드라마"
},
{
"id": "d200",
"cat": "drama",
"name": "팡팡스튜디오",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 817000,
"desc": "10대·대학생·직장인 대상 웹드라마 제작사"
},
{
"id": "d201",
"cat": "drama",
"name": "끄적끄적 Writing Down",
"yt": "@writingdown",
"ytId": null,
"ig": null,
"tt": null,
"followers": 499000,
"desc": "플레이타운 브랜드, 10~20대 현실 연애 웹드라마"
},
{
"id": "d202",
"cat": "drama",
"name": "밈고리즘",
"yt": "@mimgorithm",
"ytId": null,
"ig": null,
"tt": null,
"followers": 489000,
"desc": "'폭스클럽' 모큐멘터리 등 드라마형 코미디"
},
{
"id": "d203",
"cat": "drama",
"name": "너튜브 Neotube",
"yt": "@neotubekorea",
"ytId": null,
"ig": null,
"tt": null,
"followers": 427000,
"desc": "'좋아해요' 시리즈 스케치 코미디·드라마"
},
{
"id": "d204",
"cat": "drama",
"name": "루디스튜디오",
"yt": "@rudy.studio",
"ytId": null,
"ig": null,
"tt": null,
"followers": 385000,
"desc": "구독자 사연 기반 웹드라마 (2024년 이후 휴식)"
},
{
"id": "d205",
"cat": "drama",
"name": "LIKE 라이크",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 362000,
"desc": "치즈필름에서 독립한 세 친구의 웹드라마·쇼츠"
},
{
"id": "d206",
"cat": "drama",
"name": "찐엔딩",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 300000,
"desc": "학교 배경 성장·연애 웹드라마"
},
{
"id": "d207",
"cat": "drama",
"name": "비플레이 B-PLAY",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 210000,
"desc": "삼각관계 로맨스 등 TV급 웹드라마"
},
{
"id": "d208",
"cat": "drama",
"name": "피칸필름",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 120000,
"desc": "쉐어하우스 대학생 3인의 일상 웹드라마"
},
{
"id": "d209",
"cat": "drama",
"name": "심스틸러",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 120000,
"desc": "코미디언 출연 스케치형 웹드라마"
},
{
"id": "d210",
"cat": "drama",
"name": "석필름 SUKFILM",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 110000,
"desc": "로맨스 웹드라마"
},
{
"id": "d211",
"cat": "drama",
"name": "수낫수 스튜디오",
"yt": "@SOONOTSUE",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "퀴어·GL 소재 웹드라마, '여자에게 설레는 편' 1,000만 뷰"
},
{
"id": "d212",
"cat": "drama",
"name": "IZZANA STUDIO",
"yt": "@IZZANASTUDIO",
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "웹드라마 제작 스튜디오"
},
{
"id": "d213",
"cat": "drama",
"name": "비글루 Vigloo",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "스푼랩스의 세로형 숏드라마 플랫폼"
},
{
"id": "d214",
"cat": "drama",
"name": "탑릴스 TopReels",
"yt": null,
"ytId": null,
"ig": null,
"tt": null,
"followers": 0,
"desc": "한국 숏드라마 플랫폼"
}
];
